### ISSUE TITLE
Match each pattern only once per file

### ISSUE THREAD

**Issue by adamfarquhar** [openpreserve/fido#10]
Many signatures re-use patterns.  For example, the PDFs all have the same end-of-file pattern.  The Zip family (jar, zip, odf, ooxml, ...) all share some patterns.  It would be easy to check these once per file.
A better approach might be to change the signature approach so that these tests are moved up to a super-type and only stored once in Pronom.  This would help to avoid inconsistencies between signatures.

**Comment by carlwilson** [comment]
Closed due lack of recent activity.
