### ISSUE TITLE
performance on x-fmt/387

### ISSUE THREAD

**Issue by schaeferc-si** [openpreserve/fido#112]
Fido 1.3.6, v90 performs very slowly identifying x-fmt/387.  Took about 25 minutes to identify 14 large .tif files (size in total: ~245MB).

**Comment by jrwdunham** [comment]
Verified that the bug is fixed on Python 2.7.6:

    Python 2.7.6 (default, May  4 2015, 17:34:28) 
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import re
    >>> re.search('(?s)\A.{0,65536}test', 'test')
    <_sre.SRE_Match object at 0x1054003d8>

and on Python 3.6.0:

    $ python
    Python 3.6.0 (default, Oct 24 2017, 17:36:59) 
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import re
    >>> re.search('(?s)\A.{0,65536}test', 'test')
    <_sre.SRE_Match object; span=(0, 4), match='test'>

**Comment by jrwdunham** [comment]
@schaeferc-si You may want to check out https://github.com/openpreserve/fido/pull/123 and test whether it solves this issue for you. I believe it should.
