### ISSUE TITLE
`install_requires` pins six to specific version 1.10.0

### ISSUE THREAD

**Issue by sevein** [openpreserve/fido#140]
It is not considered best practice to use `install_requires` to pin dependencies to specific versions.

fido pins the `six` package to `1.10.0`, see:

https://github.com/openpreserve/fido/blob/dfdb9b20bb67c7d449b72ef81386fa9aaa419a4a/setup.py#L26-L30

Users installing fido in environments where a newer version of `six` is also required could see a warning like the following:

    opf-fido 1.3.9 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.

I suggest to replace the requirement so we only indicate the lower and upper bounds, e.g.:

    six >= 1.10.0, < 2

Thoughts?

**Comment by ablwr** [comment]
I see how it can be intentional to pin to specific versions, particularly if we are working with older versions of bigger dependencies like Django, for instance. But for this library (and because we get some annoying conflicts like you point out), I think we should do as you suggest.
