### ISSUE TITLE
Release new version with correct default format file?

### ISSUE THREAD

**Issue by OskarPersson** [openpreserve/fido#148]
#146 was merged months ago but there hasn't been a release including it yet

**Comment by ablwr** [comment]
https://github.com/openpreserve/fido/releases/tag/v1.3.12-94 contains https://github.com/openpreserve/fido/commit/8b0c0878ded3cb03a6b331f4bd0180f56982f2d7 ?

**Comment by carlwilson** [comment]
We're working on the release process currently, as soon as it's ready it will be with you. Closing this as it will be addressed by the act of releasing.
