### ISSUE TITLE
Fido crashes when re-cursing into zip or tar files with embedded container files that aren't zip or tar

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/fido#163]
This line: https://github.com/openpreserve/fido/blob/master/fido/fido.py#L395 causes the issue. One example is a zip file with an embedded `ole` container. Fido executes the [`identify_contents method`](https://github.com/openpreserve/fido/blob/master/fido/fido.py#L382) with `type == 'ole'` and the code falls into the exception. Given the `-zip` option states: "recurse into zip and tar files" I propose the code just returns here, perhaps logging the issue on a more verbose setting. The code's done nothing more than honour the documentation and not tried to unpack an archive it can't.

My solution here is possibly simplistic but canvassing opinion on the fix.

**Comment by ablwr** [comment]
@carlwilson Would you consider this resolved by your patch #164, or would you prefer to keep this open because there could be a more robust solution?

**Comment by carlwilson** [comment]
@ablwr I think my fix covers this nicely TBH for now. FIDO does as advertised on containers it can unpack and skips those it can't. Feel free to close
