### ISSUE TITLE
Question re: regex used in FIDO

### ISSUE THREAD

**Issue by jnik-aarhus** [openpreserve/fido#168]
Hi there!

I am currently working as a software developer for the City Archives in Aarhus, Denmark, and we are interested in incorporating PRONOM signatures in our work. To that end, I have been perusing several tools taking advantage of DROID signature files, `fido` included.

It is my understanding that you use regex in order to match byte sequences found in files. Per the [DROID paper](http://www.nationalarchives.gov.uk/aboutapps/fileformat/pdf/automatic_format_identification.pdf), PRONOM signatures are born as byte sequences with wildcards and then preprocessed. Do you backwards engineer the resulting DROID signature file in order to translate to regex for use in `fido`, or do you obtain the original PRONOM signatures from somewhere?

Thank you in advance for taking the time to answer my questions!

-- Nina

**Comment by mistydemeo** [comment]
Hi Nina! You're correct that FIDO uses regexes. These are generated using DROID's signature files as a basis; we have code which transforms them from PRONOM's signatures into regular expressions, which you can find here: https://github.com/openpreserve/fido/blob/master/fido/prepare.py

**Comment by jnik-aarhus** [comment]
Hi Misty, thank you for the quick reply!
Do you know why The National Archives do not publish the original PRONOM signatures along with the preprocessed files?

**Comment by jnik-aarhus** [comment]
Please disregard my last question, I found the web service now. Thank you for your help, I'll close this issue now. :)
