### ISSUE TITLE
1.4.1 wheel does not match source, missing format file

### ISSUE THREAD

**Issue by OskarPersson** [openpreserve/fido#184]
The wheel on PyPi for 1.4.1 contains both `formats-v95.xml` and `formats-v96.xml` in the `conf` directory while the source tar.gz only contains `formats-v96.xml`.

The [default format files list](https://github.com/openpreserve/fido/blob/master/fido/fido.py#L42) was not updated in #181 and therefore only works when the wheel is installed and not when installed from source.

**Comment by ablwr** [comment]
woof, thanks @OskarPersson -- I'll send a patch.
