### ISSUE TITLE
olefile as a dependency at version >= 0.46

### ISSUE THREAD

**Issue by jamiepb** [openpreserve/fido#198]
Hello,

I ran into the following error when running fido 1.4.1 on a .doc file (identified as Microsoft Word 97-2003 by Windows 10):

> Traceback (most recent call last):
  File "/usr/local/bin/fido", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/fido/fido.py", line 861, in main
    fido.identify_file(file, extension=not args.noextension)
  File "/usr/local/lib/python3.6/dist-packages/fido/fido.py", line 362, in identify_file
    container_matches = self.match_container("OLE2", OlePackage, filename, container_file)
  File "/usr/local/lib/python3.6/dist-packages/fido/fido.py", line 211, in match_container
    puids = klass(file, self.extract_signatures(signature_file, signature_type=signature_type)).detect_formats()
  File "/usr/local/lib/python3.6/dist-packages/fido/package.py", line 40, in detect_formats
    with olefile.OleFileIO(self.ole) as ole:
AttributeError: __enter__

I was using ole 0.45.1 and once I upgraded it to 0.46, it was able to identify the file:

> FIDO v1.4.1 (formats-v96.xml, container-signature-20200121.xml, format_extensions.xml)
OK,140,fmt/111,"OLE2 Compound Document Format","OLE2 Compound Document Format",22528,"Desktop/Easley_Backup_appraisal_bag/Easley_backup_20110930/August 11/Education Video Transcript.doc","None","signature"
FIDO: Processed      1 files in 209.69 msec,  5 files/sec

Would you consider testing having olefile 0.46 as a dependency for fido?

Thank you,

Jamie Patrick-Burns

**Comment by mistydemeo** [comment]
Thanks for reporting this issue! The version has been updated in #195, but there hasn't been a new release that includes that change yet. This'll be fixed when the next version comes out.

**Comment by carlwilson** [comment]
#195 closes this issue in v1.6
