### ISSUE TITLE
Review recent code that extends fido XML to include more registry data

### ISSUE THREAD

**Issue by techmaurice** [openpreserve/fido#27]
Submitted by Andrew Jackson:

To clarify, I added experimental code that pulls more details out of the Format Record and populates an additional 'details' section in the Fido signature file. It looks like this:

```
<details>
      <dc:description>This is an outline record only, and requires further details, research or authentication to provide information that will enable users to further understand the format and to assess digital preservation risks associated with it if appropriate. If you are able to help by supplying any additional information concerning this entry, please return to the main PRONOM page and select &#226;&#128;&#152;Add an Entry&#226;&#128;&#153;.</dc:description>
      <dcterms:available />
      <dc:creator />
      <dcterms:publisher />
      <content_type />
      <record_metadata>
        <status>unknown</status>
        <dc:creator>Digital Preservation Department / The National Archives</dc:creator>
        <dcterms:created>11 Mar 2005</dcterms:created>
        <dcterms:modified>02 Aug 2005</dcterms:modified>
        <dc:description />
      </record_metadata>
    </details>
```

The problem is that it's not clear that this is a good idea, and it may slow down parsing unnecessarily. I am increasingly of the opinion that most of this data should be in a true format registry, and that identification tools should only include a minimal amount of data and refer the user to the registry for these kind of details.

Having said that, this is not a critical issue for Fido as it only slows things down, at worst.

Original issue: [FIDO-2](http://jira.opf-labs.org/browse/FIDO-2)

**Comment by carlwilson** [comment]
Closed due lack of recent activity.
