### ISSUE TITLE
Determining file formats within a ZIP file gives an [Error 2] but then correctly determines the format

### ISSUE THREAD

**Issue by techmaurice** [openpreserve/fido#28]
fido.py Personal_Files_Folder.zip yields:

OK,168,x-fmt/263,"ZIP Format","ZIP format",294895,"Personal_Files_Folder.zip","application/zip","signature"
OK,6,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",3919,"Personal_Files_Folder.zip!Personal_Files_Folder/BIBORGAN.SC","None","signature"
[Errno 2] No such file or directory: 'Personal_Files_Folder.zip!Personal_Files_Folder/CH7.RD'
OK,11,fmt/111,"OLE2 Compound Document Format","OLE2 Compound Document Format",149504,"Personal_Files_Folder.zip!Personal_Files_Folder/CH7.RD","None","signature"
OK,6,fmt/393,"Borland Reflex flat datafile","Borland Reflex flat datafile",10808,"Personal_Files_Folder.zip!Personal_Files_Folder/COURTNE.RXD","None","signature"
OK,6,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",7400,"Personal_Files_Folder.zip!Personal_Files_Folder/DELIVERY","None","signature"
OK,20,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",156689,"Personal_Files_Folder.zip!Personal_Files_Folder/DIRMIN2","None","signature"
OK,10,x-fmt/22,"7-bit ASCII Text","External",30464,"Personal_Files_Folder.zip!Personal_Files_Folder/INDEX.ASC","text/plain","extension"
OK,10,x-fmt/283,"8-bit ASCII Text","External",30464,"Personal_Files_Folder.zip!Personal_Files_Folder/INDEX.ASC","text/plain","extension"
OK,6,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",9915,"Personal_Files_Folder.zip!Personal_Files_Folder/MODULE1.RH","None","signature"
OK,8,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",27580,"Personal_Files_Folder.zip!Personal_Files_Folder/NZ&AUST.WP","None","signature"
OK,26,x-fmt/8,"dBASE Database","dBase Table Version II (date last updated (month (1-12), day (1-31), year)",819200,"Personal_Files_Folder.zip!Personal_Files_Folder/NZPN.DBF","None","signature"
KO,23,,,,220672,"Personal_Files_Folder.zip!Personal_Files_Folder/NZPNPERS.NDX",,"fail"
OK,6,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",3062,"Personal_Files_Folder.zip!Personal_Files_Folder/PTCHALMI.WP","None","signature"
OK,12,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",59816,"Personal_Files_Folder.zip!Personal_Files_Folder/SEMINAR.DOC","None","signature"
OK,9,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",30937,"Personal_Files_Folder.zip!Personal_Files_Folder/SESSION2","None","signature"
OK,6,x-fmt/394,"WordPerfect for MS-DOS/Windows Document","WordPerfect 5.1",7494,"Personal_Files_Folder.zip!Personal_Files_Folder/TOWNNUMB","None","signature"
OK,17,fmt/125,"Microsoft Powerpoint Presentation","Powerpoint 95",76800,"Personal_Files_Folder.zip!Personal_Files_Folder/Week7.ppt","application/vnd.ms-powerpoint","signature"

The second file within the zip is CH7.RD which fido claims is not found, but then it successfully determines the format. Also, running fido.py on the unzipped files from this .zip works fine.

Maurice Bouchard commented:

```
The command I issued should read:
fido.py -zip Personal_Files_Folder.zip

sorry for the confusion.
```

Maurice de Rooij commented:

```
Thank you very much for reporting.

This issue will be fixed in the next commit.

The second file within the zip is CH7.RD which fido claims is not found, but then it successfully determines the format. Also, running fido.py on the unzipped files from this .zip works fine.

The read error is due to the fact that the function which analyzes container files is not yet able to recurse into zipfiles.
The successfull determination of the format afterwards is because that result is originally the result that triggered the container function.
```

Original issue: [FIDO-28](http://jira.opf-labs.org/browse/FIDO-28)

**Comment by carlwilson** [comment]
Closed due lack of recent activity.
