### ISSUE TITLE
wrong result for odt into zip

### ISSUE THREAD

**Issue by florianajir** [openpreserve/fido#35]
A scan in an archive (with the -zip arg) which contain an odt file identify the odt as a ZIP Format (wrong) and analyze all the objects into (jpg, xml, etc.)

Strangely, when I scan the same odt file with the -zip arg, fido detect normally the OpenDocument Text format without searching into.

Maybe you can create an argument to scan into odt container but disable it by default when scanning an archive.

Anyway, the result ZIP Format is wrong for OpenDocument in a zip.

**Comment by carlwilson** [comment]
Closed due lack of recent activity.
