### ISSUE TITLE
Adobe Illustrator 14 file identified as PDF 1.5, not AI

### ISSUE THREAD

**Issue by mistydemeo** [openpreserve/fido#41]
This Adobe Illustrator sample is being misidentified in fido 1.3.1 using the PRONOM v70 signatures: https://github.com/artefactual/archivematica-sampledata/raw/master/SampleTransfers/Images/BBhelmet.ai

The file is an Illustrator 14 (CS4) file (fmt/563), but is being identified as PDF 1.5 (fmt/19). This isn't actually wrong per se (since AI files are a superset of PDF), but isn't fully accurate. DROID 6.1.2, using the same v70 signature files, correctly identifies the file as fmt/563.

**Comment by carlwilson** [comment]
Closed due lack of recent activity.
