### ISSUE TITLE
Fido identifies PowerPoint file as Excel

### ISSUE THREAD

**Issue by mistydemeo** [openpreserve/fido#43]
## Dev Effort
0.5D

## Description
The following file is misidentified by fido via its container signature: https://drive.google.com/file/d/0B_ULgjJDmvCkRGdzREc1WFB6Ym8/edit?usp=sharing (File => Download will download the original unconverted document.)

fido returns the following ID:

> OK,550,fmt/61,"Microsoft Excel 97 Workbook (xls)","BIFF 8 & 8X Workbook (generic)",2706944,"d775b31c-b627-4f7c-908a-9a3502e18e69_Archivematica-0.6-alpha-screenshots.ppt","application/vnd.ms-excel","container"

Whereas DROID returns:

> /home/mistydemeo/artefactual/archivematica/src/MCPServer/share/sharedDirectoryStructure/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/maildir-dd365c04-0c91-4bbc-9e4a-b24c27533af1/objects/attachments/_Gmail_.Sent_Mail/cur/d775b31c-b627-4f7c-908a-9a3502e18e69_Archivematica-0.6-alpha-screenshots.ppt,fmt/126

fmt/126 (Microsoft Powerpoint Presentation (97-XP)) is the correct ID for this file.

Looks like this is a bufsize size issue again (cf. #41) - if I increase the buffer size to 1MB, it's identified. Is this just expected behaviour in the default config?

**Comment by ablwr** [comment]
The good news is FIDO doesn't think this file is an Excel file anymore; the bad news is it just claims it as an OLE unless the bufsize is immensely increased.

**Comment by carlwilson** [comment]
@ablwr How immensely??

**Comment by carlwilson** [comment]
@ablwr & @mistydemeo I've just exchanged a couple of emails with @sevein, and we think this is probably just a documentation issue. It's buried on the OPF Wiki section a bit, and that's been down, but it's there. It should be more prominent or better organised. I will suggest some ideas here.

**Comment by carlwilson** [comment]
Config issue rather than functionality, closing.
