### ISSUE TITLE
invalid SRE code

### ISSUE THREAD

**Issue by florianajir** [openpreserve/fido#55]
## Dev Effort
0.5D

## Description
I don't know why, since few days fido miss docx identification and found zip in his place and a message 'invalid SRE code' appear on beginning. As I read in the previous issue that is look like 'invalid SRE code' is a bug in Python v2.7.3, so I tested with Python v2.7.6 : no more 'invalid SRE code' but docx not recognize though.. : 

```
FIDO v1.3.1 (formats-v78.xml, container-signature-20130501.xml, format_extensions.xml)
invalid SRE code
OK,9,x-fmt/263,"ZIP Format","ZIP format",3734,"/home/fajir/test.docx","application/zip","signature"
```

Altough the first item (customized with the pronom puid as replace of fido-puid) has priority over x-fmt/263 in my conf/format_extensions.xml : 

```
<format>
<puid>fmt/412</puid>
<name>Microsoft Office Open XML - Word</name>
<mime>application/vnd.openxmlformats-officedocument.wordprocessingml.document</mime>
<extension>docx</extension>
<has_priority_over>x-fmt/263</has_priority_over>
<has_priority_over>fmt/189</has_priority_over>
<signature>
<name>Microsoft Office Open XML - Word</name>
<pattern><position>BOF</position><regex>(?s)\APK\x03\x04</regex></pattern>
<pattern><position>BOF</position><regex>(?s)\A.{30}\[Content_Types\]\.xml \xa2</regex></pattern>
<pattern><position>EOF</position><regex>(?s)\x00\x00word/.{1,20}\.xmlPK\x01\x02\x2d.{0,2000}\Z</regex></pattern>
</signature>
</format>
```

Any help ?

**Comment by ablwr** [comment]
This seems to be an issue that was corrected some time ago, in the distance past. If not, please open this issue again and provide a sample file.
