### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Hwesta** [openpreserve/fido#79]
## Dev Effort
10D

## Description
Improve Python3 support.

Some inital work was done in #67  but as issues like #78 suggest it still needs some attention.

To Do:
- [ ] Check for bytes vs str mismatch (eg #67)
- [ ] Fix update_signatures to not use deprecated httplib.HTTP
- [ ] ... other?

**Comment by Hwesta** [comment]
See also #26

**Comment by bitsgalore** [comment]
Also worth mentioning that Python 2 support will stop in 2020: <https://pythonclock.org/>

**Comment by carlwilson** [comment]
To be done in conjunction #151 (testing) so that we're sure we've not broken anything as we go.

**Comment by sallain** [comment]
FYI - we're currently working on a Python 3 upgrade for Archivematica, so I've opened archivematica/Issues#847 as a placeholder so that Fido has some visibility in our project management tooling.
