### ISSUE TITLE
Signature file improvements?

### ISSUE THREAD

**Issue by Hwesta** [openpreserve/fido#80]
Some ideas for improving how signature files are handled

One idea is to use [Roy](https://github.com/richardlehane/siegfried/wiki/Building-a-signature-file-with-ROY) to create signature files. This would allow access to a wider range of formats since it can include information from Apache Tika, freedesktop.org MIME-info and Library of Congress FDDs.

Another is to use DROID's signature files directly, since they're what PRONOM offers by default, and not have to perform a transformation. This may be a simpler change than above.

Other suggestions welcome!

**Comment by carlwilson** [comment]
This needs decomposing in the light of other signature work, @carlwilson to pick up with sig file review.

**Comment by carlwilson** [comment]
> Another is to use DROID's signature files directly, since they're what PRONOM offers by default, and not have to perform a transformation. This may be a simpler change than above.

This isn't the case because the reason for compiling the sigs is that they can be then used with a standard regular expression engine. Using the PRONOM sigs "raw" would necessitate the development of a matching algorithm instead.

The idea of using Roy to allow other sig sources is definitely interesting though.

**Comment by carlwilson** [comment]
Hackathon 2023 Review: Not selected for initial tasks. Adding support for multiple signature sources is likely a prerequisite. Doing that well/properly is a task in itself and should be logged as a feature request.

**Comment by carlwilson** [comment]
Closing this as is covered by #218
