### ISSUE TITLE
Fix fetching example URLs when updating signature

### ISSUE THREAD

**Issue by Hwesta** [openpreserve/fido#84]
When updating signatures, if the format has a ReferenceFileIdentifier of type URL, we include a reference to it, including fetching it and calculating a checksum.  However, ReferenceFileIdentifier is not consistent in its meaning or format.

Eg from PRONOM 88 where fmt/11 starts with a www, and the URL is actually a PNG

``` xml
<ReferenceFileIdentifier>
  <Identifier>www.w3.org/Graphics/PNG/nurbcup2si.png</Identifier>
  <IdentifierType>URL</IdentifierType>
</ReferenceFileIdentifier>
...
<ReferenceFileIdentifier>
  <Identifier>www.w3.org/Graphics/PNG/666.png</Identifier>
  <IdentifierType>URL</IdentifierType>
</ReferenceFileIdentifier>
```

compared to fmt/569, which starts with http:// and is a HTML page linking to examples

``` xml
<ReferenceFileIdentifier>
  <Identifier>http://www.matroska.org/downloads/test_w1.html</Identifier>
  <IdentifierType>URL</IdentifierType>
</ReferenceFileIdentifier>
```

When parsing it, we prepend http:// and fetch it, which breaks with `http://www.matroska.org/downloads/test_w1.html`

``` python
url = "http://" + get_text_tna(id, 'Identifier')
...
sock = urlopen(url)
```

Options include removing the examples and checksums from formats-v##.xml, or adding error handling around that section.

**Comment by jhsimpson** [comment]
This issue appears to be fixed by #101
