### ISSUE TITLE
1.3.5 release

### ISSUE THREAD

**Issue by Hwesta** [openpreserve/fido#91]
I'm planning on making a 1.3.5-88 release this week with the PRONOM v88 signature files. 

My proposed release notes are:
### This release:

* Update the PRONOM signature files to version 88 in #81
* Thanks to @ worr for testing and reporting 2 bugs related to zipfiles in #76 and #77
* Thank to @ OskarPersson for fixing a crash on zero byte files with non-ascii name in #88 
* Fix the URL to fetch signature files from in #81 
* Remove old PRONOM signature files and only keep the most recent version around in #86 
* Update README installation instructions & convert to markdown in #87
* Remove reload & sys.setdefaultencoding to make Python 3 support easier in #82 
* Update to fix flake8 error in #90 

@carlwilson @mistydemeo Do you have any feedback on the release version/release notes/timeline/other PRs that should make the cut?

Thanks!

Edit: Updated release notes to include 90
Edit: Include 88

**Comment by mistydemeo** [comment]
Sorry for not replying sooner. This sounds good to me!

I think #90 is sufficiently simple to get in. What are you feeling about #88?

**Comment by Hwesta** [comment]
Great, I merged #90.  I'm happy merging the two commits from #88 that don't duplicate 90 as well.

**Comment by OskarPersson** [comment]
@Hwesta Should I revert the last commit in #88 ?

**Comment by Hwesta** [comment]
@OskarPersson please, since it ended up being duplicated by 90.

**Comment by OskarPersson** [comment]
@Hwesta Done

**Comment by Hwesta** [comment]
Merged 88 as well, and updated the release notes. I think it's ready to go now.

**Comment by mistydemeo** [comment]
👍

**Comment by Hwesta** [comment]
Release tagged - will build packages & put on PyPI this week.

**Comment by OskarPersson** [comment]
Any news on the PyPI update?

**Comment by jhsimpson** [comment]
I have uploaded a test package to pypitest.  One more PR to merge before we can upload to pypi officially:
https://github.com/openpreserve/fido/pull/92

Should be done on Monday.

**Comment by jhsimpson** [comment]
PR92 got reviewed and merged, and PyPI has been updated.

https://pypi.python.org/pypi/opf-fido/1.3.5
